### ISSUE TITLE
Add htmlFile in onChange callback

### ISSUE THREAD

**Issue by Clemios** [BEE-Plugin/Bee-plugin-official#107]
**Is your feature request related to a problem? Please describe.**
In order to save email/page onChange we need htmlFile

**Describe the solution you'd like**
It could be nice to have htmlFile in onChange callback like for onSave callback

**Describe alternatives you've considered**
In order to achieve this I considered to use Content Services API to get html from json

**Comment by davidesamp** [comment]
Hi @Clemios,

Can you please describe your scenario better ? what goal are you trying to achieve ?
