### ISSUE TITLE
Creating Bee instance with token as string doesn't work

### ISSUE THREAD

**Issue by simcen** [BEE-Plugin/Bee-plugin-official#109]
**Describe the bug**
The type definition of Bee class requires "token" parameter to be string (https://github.com/BEE-Plugin/Bee-plugin-official/blob/11f2bfaf45e1862d1a2495f89cc9cb69956e93e0/src/index.ts#L55) but the editor won't start or return any error message in that case. When providing token as object, it actually works fine.

**To Reproduce**
1. Create Bee instance with token as string and launch editor --> bee.start() doesn't do anything, no erros in console or in onError or onWarning 
2. Create Bee instance with token as object and launch editor --> bee.start() actually works fine

**Expected behavior**
Type definition of token argument in Bee class should be typed object instead of string

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 111

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by davidesamp** [comment]
Hi @simcen, thank for you report! 
We published a new version ([v2.1.4](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/2.1.4)) where we fixed the issue you reported.
