### ISSUE TITLE
Incorrect type declaration in reload() and load()

### ISSUE THREAD

**Issue by simcen** [BEE-Plugin/Bee-plugin-official#114]
https://github.com/BEE-Plugin/Bee-plugin-official/blob/8a0a7d71120940322977b3d6bcb484c8acdc54a0/src/index.ts#L165
is:
`reload = (template: Record<string, unknown>, options?: IBeeOptions) => this.executeAction(RELOAD, template, options)`

should be:
`reload = (template: IEntityContentJson, options?: IBeeOptions) => this.executeAction(RELOAD, template, options)`

https://github.com/BEE-Plugin/Bee-plugin-official/blob/8a0a7d71120940322977b3d6bcb484c8acdc54a0/src/index.ts#L143
is:
`load = (template: Record<string, unknown>) => this.executeAction(LOAD, template)`

should be:
`load = (template: IEntityContentJson) => this.executeAction(LOAD, template)`

**Comment by davidesamp** [comment]
Hi @simcen,

Thanks for you report, we released a new version [2.1.5](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/2.1.5)  that resolves this issue.
