### ISSUE TITLE
Behaviors instead of  behaviour in  CustomRowConfiguration

### ISSUE THREAD

**Issue by liron58** [BEE-Plugin/Bee-plugin-official#115]
The name of the field on the typing of CustomRowConfiguration is wrong and not working , need to use Behaviors instead of behaviour.
![image](https://user-images.githubusercontent.com/28891740/233839552-74586dcd-2a43-4317-8a13-a2de95f79676.png)
![image](https://user-images.githubusercontent.com/28891740/233839517-4b3ede69-bbcd-4a30-b84d-2c11f5dd0d1d.png)

**Comment by davidesamp** [comment]
Hi @liron58,

Thanks for you report, we released a new version [2.1.5](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/2.1.5)  that resolves this issue.
