### ISSUE TITLE
After scrolling the background screen to bottom, "merge tags" modal is not scrollable and screen gets shifted upwards when user try to scroll the modal.

### ISSUE THREAD

**Issue by alidiplana** [BEE-Plugin/Bee-plugin-official#119]
**Describe the bug**
After scrolling the background screen to bottom, on  "merge tags" modal is not scrollable and screen gets shifted upwards when user try to scroll the modal.

**To Reproduce**
1. Go to 'text editor'
2. Click on 'merge tags'
3. Scroll down to by clicking on scroll 

**Expected behavior**
scroll should be scroll able 

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu, mac]

**Comment by davidesamp** [comment]
Hi @alidiplana,

Thanks for your report. 
Unfortunately this problem does not affect this project that is just a wrapper of [Bee Plugin](https://developers.beefree.io/). You can report the same bug to the BeePlugin's support following [this guide](https://devportal.beefree.io/hc/en-us/articles/4805287369490-How-do-I-get-support-for-BEE-Plugin-).
