### ISSUE TITLE
Where is this fix that appear on the site?

### ISSUE THREAD

**Issue by romuloctba** [BEE-Plugin/Bee-plugin-official#124]
Hi, how are you doing?

I'd like to ask you where can I find more information about the following update, marked as "fix", that I can see in the plugin's website

![image](https://github.com/BEE-Plugin/Bee-plugin-official/assets/2955932/bcf2321f-8ad4-47bc-969a-7d07b9cda3d8)

I am facing a particular issue, that is a template being saved with different content than expected, so I would like to understand if the fix above could solve my problem, or if its not related.

Thank you

**Comment by davidesamp** [comment]
Hi @romuloctba,

For this kind of questions you can contact directly the Bee Plugin support following [this guide](https://devportal.beefree.io/hc/en-us/articles/4805287369490-How-do-I-get-support-for-BEE-Plugin-).
