### ISSUE TITLE
Own File Storage  Azure Support

### ISSUE THREAD

**Issue by zahid492** [BEE-Plugin/Bee-plugin-official#2]
Do your team have any plan to integrate Azure support for file storage, at now you have just only provide Amazon AWS support.

**Comment by BEE-Plugin** [comment]
Hi zahid492,
sorry for the late response.
Unfortunately not yet now. The good news is that you can create your own File System Provider that can interact with your preferred storage system.
Let me know if I can help you with additional information on this topic!
Thanks!
