### ISSUE TITLE
Autosave timeout is triggered immediately in V3

### ISSUE THREAD

**Issue by graham-saunders** [BEE-Plugin/Bee-plugin-official#3]
BEE V3 plugin's onAutoSave parameter is triggered immediately and does not respect the autosave parameter value.

The docs show that this is still supported - can we please get some eyes on this? It's preventing me from updating to V3

**Comment by BEE-Plugin** [comment]
Hi @graham-saunders - Thank you for raising this issue.  Since this is not related to this NPM package and you've opened a support request, we're going to go ahead and close this issue in Github.  We can continue to discuss this via your support ticket. Thanks again!

**Comment by Martirosian** [comment]
Hi @BEE-Plugin Can you please tell me if this issue is resolved? I'm also having the same issue, `autosave: false` or `autosave: NUMBER` does nothing, seems like the editor is auto-saving _on change_
