### ISSUE TITLE
 "window is not defined" error is coming 

### ISSUE THREAD

**Issue by Sakshi-kataria-Capillary** [BEE-Plugin/Bee-plugin-official#4]
I have just imported this package
const Bee = require('@mailupinc/bee-plugin');
it is giving error  error: uncaughtException: window is not defined at  /node_modules/@mailupinc/bee-plugin/dist/index.js

**Comment by Sylchauf** [comment]
Any updates ?

Same issue with Meteor (v1.11.1)

**Comment by rchasman** [comment]
same issue here

**Comment by diogobeda** [comment]
@Sakshi-kataria-Capillary are you rendering that on the server?
What I did to fix that is requiring the library out of the SSR scope. If you're using React it should be, for example, in `componentDidMount`.

```js
componentDidMount() {
  const Bee = require('@mailupinc/bee-plugin').default;
}
```

**Comment by davidesamp** [comment]
Hi @Sakshi-kataria-Capillary,
Can you please check if the issue is still present on the latest stable version of the npm [package](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/1.5.3)  ?
