### ISSUE TITLE
How to set local css file using customCss props?

### ISSUE THREAD

**Issue by olgakozich** [BEE-Plugin/Bee-plugin-official#46]
How to set local css file using customCss props?

**Comment by davidesamp** [comment]
Hi @olgakozich,
according to the [documentation](https://docs.beefree.io/custom-css/) you should specify your customCss as url. 
So, you could expose your css in your application and point it in your configuration:

```
const beeConfig = {
  customCss: 'http://localhost:8080/mycustom.css',
  ...
}
```

**Comment by olgakozich** [comment]
@davidesamp Thanks a lot!

**Comment by davidesamp** [comment]
> @davidesamp Thanks a lot!
You're welcome @olgakozich
