### ISSUE TITLE
Issues while compiling/bundling with yarn

### ISSUE THREAD

**Issue by jaspervanson** [BEE-Plugin/Bee-plugin-official#53]
### Describe the bug
I am running into issues updating the bee-plugin from version `1.2.2` to version `1.5.1` (including it's dependencies).
When I try to run the plugin in our existing Angular application we get the following errors from the 'bee-plugin' package:
```
ERROR in [./node_modules/@mailupinc/bee-plugin/dist/index.es.js](mailto:./node_modules/@mailupinc/bee-plugin/dist/index.es.js)
Module not found: Error: Can't resolve 'http' in 'C:\DEV\bulkemail-frontend\node_modules\@mailupinc\bee-plugin\dist'
ERROR in [./node_modules/@mailupinc/bee-plugin/dist/index.es.js](mailto:./node_modules/@mailupinc/bee-plugin/dist/index.es.js)
Module not found: Error: Can't resolve 'https' in 'C:\DEV\bulkemail-frontend\node_modules\@mailupinc\bee-plugin\dist'
ERROR in [./node_modules/@mailupinc/bee-plugin/dist/index.es.js](mailto:./node_modules/@mailupinc/bee-plugin/dist/index.es.js)
Module not found: Error: Can't resolve 'zlib' in 'C:\DEV\bulkemail-frontend\node_modules\@mailupinc\bee-plugin\dist'
```
### Screenshot:
![image](https://user-images.githubusercontent.com/57749693/153600902-808457f1-9f30-453a-9aab-a995d8a00ea4.png)

### What I've done
I tried 2 things:
1. Change the version number to 1.5.1 in 'package.json'
2. yarn install
3. yarn start

This didn't work so I went for a clean install:
1. Remove the 'bee-plugin' dependency from 'package.json'
2. Delete all node-modules
3. yarn add @mailupinc/bee-plugin
4. yarn install
5. yarn start (this is the step where the issue is popping up)

### Development environment setup
- Node.js v16.5.0
- Webpack v4.42.0

### Previous contact with Bee
From my previous contact with Bee I got asked the to rename an `.env.sample` file in the cloned folder to `.env`.
![bee](https://user-images.githubusercontent.com/57749693/153605406-69c1fd2e-2dcf-4565-8c3a-54d5f10a321e.png)
Unfortunately I was not able to find this folder/file in the package. (I don't think this was necessary for my use case anyway)

I wanted to share this issue and hopefully find a fix for, so that we can make sure that we have the latest and greatest 'bee-plugin' package.

**Comment by davidesamp** [comment]
Hi @jaspervanson this issue has been resolved  since the [v1.5.3](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/1.5.3).

You can find [here](https://codesandbox.io/s/hofiuy) on our official Codesandox account a sample integration similar to your configuration
