### ISSUE TITLE
Maximum call stack size exceeded at resizePanel

### ISSUE THREAD

**Issue by sophia-ma** [BEE-Plugin/Bee-plugin-official#56]
**Describe the bug**
I have installed the Bee Editor in a React application. See below my implementation.

```typescript
import BeePlugin from '@mailupinc/bee-plugin';

const beePlugin = new BeePlugin();

const config = {
    uid: null,
    container: 'bee-plugin-container',
    language: 'en-US',
    onLoad: () => {},
    onSave: (jsonFile, htmlFile) => {},
    onSaveAsTemplate: (jsonFile) => {},
    onSend: (htmlFile) => {},
    onError: (errorMessage) => {},
  };

useEffect(() => {
    if (beePlugin) {
           beePlugin.getToken(
               (process.env as any).REACT_APP_CLIENT_ID,
               (process.env as any).REACT_APP_CLIENT_SECRET,
            )
            .then((authData) => {
               const newConfig = { ...config, uid: authData?.userName };

               beePlugin.start(newConfig, template);
            });
    }
}, []);
```
The app crashes when we are adding content in the editor but more specifically I noticed I am getting `Maximum call stack size exceeded at resizePanel` when I am resizing the columns. Then the Bee editor stops responding and I cannot use the `onSaveAsTemplate` that's provided because I get an error that says the Bee Editor has not been started.

**Expected behaviour**
The editor shouldn't crash when resizing the columns.

**Screenshots**
<img width="745" alt="Screenshot 2022-02-21 at 12 08 22" src="https://user-images.githubusercontent.com/40169038/154952734-02b445af-db70-403b-918b-32c7bda373e5.png">

<img width="1990" alt="image" src="https://user-images.githubusercontent.com/40169038/154969395-b58dd526-afbb-49c2-87cc-54193fa73721.png">

https://user-images.githubusercontent.com/40169038/154953183-6b08bbc8-9b5a-499a-88b1-ff93ad9e6a26.mov

**Desktop (please complete the following information):**
 - macOS Monterey Version 12.2.1
 - Chrome Version: 98.0.4758.102 (Official Build) (arm64)

**Comment by davidesamp** [comment]
H @sophia-ma,

Seems something is wrong in your init flow, can you please check if the `beePlugin.start` method is called only once. You can see a sample working React + Typrescript integration on our official Codesandbox account [here](https://codesandbox.io/s/bee-plugin-react-typescript-parcel-sample-8q4rg).

**Comment by sophia-ma** [comment]
Hello @davidesamp I have used the example provided and unfortunately, I have the same problems.

These are the versions I am currently using:
```
"@mailupinc/bee-plugin": "^1.5.1",
"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "^4.0.3",
"typescript": "^4.2.4",
```

**Comment by sophia-ma** [comment]
Latest update: It seems it's only happening in Google Chrome and it doesn't affect functionality at all. Closing the issue for now. Thank you.
