### ISSUE TITLE
Typescript typings: enum BeePluginErrorCodes doesn't include code 1100 for invalid templates

### ISSUE THREAD

**Issue by edwinsummit** [BEE-Plugin/Bee-plugin-official#59]
**Describe the bug**
The 1.6.0 release of bee-plugin introduced an enum for error-codes in the Typescript typings. It doesn't include error-code 1100 for invalid templates. Typescript does not compile when you if-check on this error code in error-callbacks.

**To Reproduce**
Start Bee with a malformed template and use error callback to if-check the error-code on code 1100
For instance with this example code: 

```typescript
import Bee from "@mailupinc/bee-plugin";
import { BeePluginError, IBeeConfig } from "@mailupinc/bee-plugin/dist/types/bee";

const bee = new Bee();

const config: IBeeConfig = {
  container: "container",
  uid: "uid",
  language: "language",
  onLoad: () => {
    console.log("loaded");
  },
  onError: (error: BeePluginError) => {
    if (error.code !== 1100) {
      throw error;
    }
    console.warn("The template is malformed and cannot be loaded.");
    // In the actual code we load a default template here
  },
};

bee.start(config, { malformed: "template" } as any);
```
**Expected behavior**
Code should be compilable in Typescript, because error-code 1100 should be a valid code

**Screenshots**
![image](https://user-images.githubusercontent.com/52782844/156224568-e58871eb-dc77-4ba5-ae1c-6b895d568a49.png)

The ts-error shown in this case is: `This condition will always return 'true' since the types 'BeePluginErrorCodes | undefined' and '1100' have no overlap.ts(2367)`

**Comment by edwinsummit** [comment]
Great!!! Thanks @davidesamp! 👍

**Comment by davidesamp** [comment]
Hi @edwinsummit you're welcome !

You release the [1.6.1](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/1.6.1) of the package with this fix.
