### ISSUE TITLE
Request: TS | `IBeeConfig['onTogglePreview']` and `IBeeConfig['onPreview']` missing parameter `Status: boolean`

### ISSUE THREAD

**Issue by elliothimmelfarb** [BEE-Plugin/Bee-plugin-official#63]
**Is your feature request related to a problem? Please describe.**
`IBeeConfig['onTogglePreview']` and `IBeeConfig['onPreview']` are missing parameter `Status: boolean` as seen in documentation and observed in usage.

`https://docs.beefree.io/methods-and-events/#instance-events`:
<img width="949" alt="Screen Shot 2022-03-24 at 12 34 43 PM" src="https://user-images.githubusercontent.com/11192126/159996241-12ddc11b-d166-4e40-ad8b-ca17786af455.png">

`bee.d.ts`:
<img width="1062" alt="Screen Shot 2022-03-24 at 12 36 06 PM" src="https://user-images.githubusercontent.com/11192126/159996406-8ad8956a-1350-415c-9d65-45aca342830e.png">

`config passed to beeInstance.start()`:
<img width="466" alt="Screen Shot 2022-03-24 at 12 37 40 PM" src="https://user-images.githubusercontent.com/11192126/159996660-c44faff9-b80c-4446-9949-563851a3cbf3.png">

**Describe the solution you'd like**
Please add the parameters to the types.

**Describe alternatives you've considered**
I am currently disabling TypeScript for this line.
I could also patch the type locally.

**Additional context**
None. Thank you for getting to my last issue so quickly!

**Comment by davidesamp** [comment]
Hi @elliothimmelfarb ,

You can find the fix on the latest version of the npm package [v1.6.3](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/1.6.3).

**Comment by elliothimmelfarb** [comment]
Thank you @davidesamp! ❤️
