### ISSUE TITLE
Change "contentAreaWidth" default value

### ISSUE THREAD

**Issue by matheusslg** [BEE-Plugin/Bee-plugin-official#79]
https://github.com/BEE-Plugin/Bee-plugin-official/blob/c03fda5c66601ada8fe80aef798ca0018aee8728/src/types/bee.ts#L1518

I'm trying to change the default value for "contentAreaWidth", but it seems that's not working:

```js
contentDefaults: {
  general: {
    contentAreaWidth: '1440px'
  }
},
```

I also didn't find any docs related to this property on your docs website, can you guys help me?

**Comment by davidesamp** [comment]
Hi @matheusslg,

Thank you for you report. The documentation will be update soon, where it will be specified that the **contentAreaWidth** configuration will be effective only with blank templates otherwise the template configuration will be applied.

Is this your case ?

**Comment by matheusslg** [comment]
Sorry for the late. I solved this issue by creating a default template that loads if there's no other template to be loaded. Anyway, thanks for the support.

**Comment by matheusslg** [comment]
Hey @davidesamp, I was wondering if there's any option to set the `minContentAreaWidth` to avoid too small templates. Is that possible?
