### ISSUE TITLE
onSaveAsTemplate type declaration incorrect

### ISSUE THREAD

**Issue by ninpeng** [BEE-Plugin/Bee-plugin-official#80]
**Describe the bug**
as is
(property) onSaveAsTemplate: (jsonFile: Record<string, unknown>) => void
to be
(property) onSaveAsTemplate: (jsonFile: string) => void

**Comment by davidesamp** [comment]
Hi @ninpeng,

Thank for you report. We fixed the wrong type on the onSaveAsTemplate callback as you suggested. The version [1.9.1](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/1.9.1) of the npm package contains this fix.
