### ISSUE TITLE
How to use Bee Free Templates in Bee Plugin Editor

### ISSUE THREAD

**Issue by subhojit-me** [BEE-Plugin/Bee-plugin-official#85]
There are many templates available in bee free at [https://beefree.io/templates/], but how to integrate some of those templates to bee plugin editor.

**Comment by davidesamp** [comment]
Hi @subhojit-me,

The beefree templates must be used through the beefree.io site, JSON cannot be downloaded. But you can add some favorite templates, then by clicking on the top right button you will be redirected on your favorite templates page. Here  you should se a "Purchase these template" button, basically you have the option to buy the selected templates that will be downloaded in a BEE Plugin JSON format.

For more information you can check our support page at https://beefree.io/support/
