### ISSUE TITLE
[Feature] [Smart Merge Tags] Control whether a space is added after inserting a Smart Merge Tag

### ISSUE THREAD

**Issue by elliothimmelfarb** [BEE-Plugin/Bee-plugin-official#87]
**Is your feature request related to a problem? Please describe.**
I've noticed that after inserting a Smart Merge Tag, BeePlugin inserts a space after the Smart Merge Tag element. 

Sometimes, especially when I've already added a space before inserting the Merge Tag or when I am adding a Merge Tag to a line of text that is already spaced, the extra space that is automatically added is not needed. 

I can envision this being frustrating for our users. Since it is much easier to see when there are no spaces than when there are two, I think it makes the most sense to have the user control adding spaces, instead of adding them for the user.

**Describe the solution you'd like**
We would like a way to disable this extra space added after inserting a Smart Merge Tag. Any other workarounds will be welcome.

**Describe alternatives you've considered**
If there are no options for doing this in a more straightforward fashion, I believe there may be a way to accomplish this within the `onChange` handler in the `BeeConfig`. Perhaps if there is an `insert smart merge tag` event, we could remove the extra space after it is added.

**Additional context**
Screenshot examples:

<img width="782" alt="Screen Shot 2022-11-08 at 9 38 31 AM" src="https://user-images.githubusercontent.com/11192126/200636639-3e103a18-5b04-4e3c-908d-ddc9d3aad34b.png">
<img width="829" alt="Screen Shot 2022-11-08 at 9 38 44 AM" src="https://user-images.githubusercontent.com/11192126/200636697-8d8c564d-64e9-4432-9dfa-78b11fe570cc.png">
<img width="826" alt="Screen Shot 2022-11-08 at 9 38 59 AM" src="https://user-images.githubusercontent.com/11192126/200636709-3e400a0c-d230-4677-a543-785193282dff.png">

Thank you for taking a look at this!

**Comment by davidesamp** [comment]
Hi @elliothimmelfarb,

Thanks for you report.
This is a default behaviour, a `&nbsp;` is added right after a merge tag to cover some edge-cases of text selection/navigation with the keyboard. 
There is no way at the moment to avoid this behaviour, I reported it to our support team for a future consideration/evaluation.

**Comment by elliothimmelfarb** [comment]
Thanks for your reply and for looking into this, @davidesamp. I'll go ahead and close this issue.
