### ISSUE TITLE
TS | Please add `defaultModulesOrder` property to `IBeeConfig` as described in documentation for re-ordering Content Tiles

### ISSUE THREAD

**Issue by elliothimmelfarb** [BEE-Plugin/Bee-plugin-official#89]
**Is your feature request related to a problem? Please describe.**
The `defaultModulesOrder` property is missing from the `IBeeConfig` type. It should be present, as described in the [documentation regarding re-ordering content tiles](https://docs.beefree.io/content-tile-sorting/#re-ordering-content-tiles). 

This causes a TypeScript error with valid usage of BeePlugin within a TypeScript environment.

**Describe the solution you'd like**
Optional property `defaultModulesOrder` is added to `IBeeConfig`.

The type value could be `string[]` but it might be better to include the known content tiles as described [here](https://docs.beefree.io/content-tile-sorting/#re-ordering-content-tiles).

Perhaps it could be an abstraction of something like this (although this may not be correct):
```typescript
// ...
defaultModulesOrder?: (
  | 'Heading'
  | 'Paragraph'
  | 'List'
  | 'Image'
  | 'Button'
  | 'Divider'
  | 'Spacer'
  | 'Social'
  | 'DynamicContent'
  | 'Html'
  | 'Video'
  | 'Form'
  | 'Icons'
  | 'Menu'
  | 'Carousel'
  | 'Text'
  | string
)[]
// ...
```

**Describe alternatives you've considered**
For now, we will need to use a `// @ts-expect-error` directive on this line.

**Additional context**
<img width="2047" alt="Screen Shot 2022-11-29 at 12 24 25 PM" src="https://user-images.githubusercontent.com/11192126/204640111-c2af0ab9-52d6-449e-bec4-a63d08773f12.png">

**Comment by davidesamp** [comment]
Hi @elliothimmelfarb,
Thank you for your report! We published [v1.11.1](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/1.11.1) where we added the definition type for the property **defaultModulesOrder**. 
You can see a sample usage in the linked [PR](https://github.com/BEE-Plugin/Bee-plugin-official/pull/92).
