### ISSUE TITLE
Mobile padding settings set in  row are reset on JSON load

### ISSUE THREAD

**Issue by ninpeng** [BEE-Plugin/Bee-plugin-official#95]
**Describe the bug**
After setting the padding value in the mobile style for the row, saving it and then loading it again, the value disappears.

**To Reproduce**
1. use free version bee plugin
2. create any rows
3. PC mode set padding 20 all sides at row
4. Mobile mode set padding 5 all sides at row
5. save a json template
6. load saved json template
7. mobile mode padding setting disappeared

**Expected behavior**
The mobile padding setting value must remain.

**Screenshots**
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/12179294/214997027-b624a4b8-fbfd-4fef-ac81-9de153b4622b.png">
<set padding value>

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/12179294/214997054-92c726da-1abc-41b1-94e3-e9aa7084fbd9.png">
<After loading the saved JSON>

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version 111

**Comment by davidesamp** [comment]
Hi @ninpeng, 
We have tested your case and it works on our side, are you sure you are uploading the updated JSON ? you can also check into the JSON and see if there is the correct value you expect. You can see it under the  "mobileStyle" section belonging to the row, the column or the module in question.

Just to exclude that the problem is not during the save as template phase.

**Comment by ninpeng** [comment]
Thanks for checking @davidesamp

[email-form padding test.zip](https://github.com/BEE-Plugin/Bee-plugin-official/files/10541949/email-form.padding.test.zip)
I tested it with this JSON file and it is a free version of the plugin.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/12179294/215645693-09cf1ff6-30ad-4b1c-91ca-b73c66f0a91a.png">
The service settings are as above.

**Comment by davidesamp** [comment]
Hi @ninpeng, 

After further investigation we realized you may have run into a bug that has been fixed a few days ago, can you try again and check if it works for you too?

**Comment by ninpeng** [comment]
Thank you for your help @davidesamp,

I just checked and it works fine.
I will close this issue.
