### ISSUE TITLE
Missing definition for `addOn` in `contentDialog`

### ISSUE THREAD

**Issue by raf59** [BEE-Plugin/Bee-plugin-official#98]
**Describe the bug**
The definition for `addOn` is missing from `contentDialog` in `IBeeConfig`

**To Reproduce**
Add the `addOn` property to the `contentDialog` configuration

**Screenshots**
https://docs.beefree.io/addon-development-power-content/#the-content-dialog-method
![image](https://user-images.githubusercontent.com/51642385/218070542-5e391cce-4106-4917-93a3-2072d5632672.png)
![image](https://user-images.githubusercontent.com/51642385/218071128-4c47bbda-21fa-469d-adeb-d32967acaab5.png)

**Comment by davidesamp** [comment]
Hi @raf59,

Thanks for you report, we're working on it and soon we will release a new version containing the fix. 
In the meanwhile we published an unstable version [v2.1.0-chore-missing-types.0](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/2.1.0-chore-missing-types.0)  where you can find the new type definition for the **addOn** contentDialog .

**Comment by raf59** [comment]
Great!
Thank you so much for taking care of this so quickly.

**Comment by davidesamp** [comment]
Released stable version [v2.1.0](https://www.npmjs.com/package/@mailupinc/bee-plugin/v/2.1.0).
